### ISSUE TITLE
Attachment tag raises an ArgumentError

### ISSUE THREAD

**Issue by agis** [operable/gbexec#2]
I may be doing something completely wrong here but here we go:

Given the following template file:
```
~$glossary~
~attachment color="green"~
foo
~end~
```

and the following data file:
```
{ "glossary": "foo" }
```

I get the following error:

```shell
$ bin/gbexec -s template2 data2 |pbcopy
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[%{"color" => "#008000", "fallback" => "foo", "mrkdwn_in" => ["text"], "text" => "foo"}]

    (elixir) lib/list.ex:624: List.to_string/1
    (greenbar_exec) lib/greenbar_exec.ex:75: GreenbarExec.display_results/2
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by christophermaier** [comment]
@agis is this still an issue?

**Comment by nmohoric** [comment]
I've tested this locally and can't reproduce so maybe it has been fixed.

**Comment by agis** [comment]
Not sure if the original issue is a valid usage, so I guess we can close this.
